import "./global.css";
import Providers from "./providers";
import { ToastProvider } from "@/components/ui/toast-provider";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "Welcome to frontend",
  description: "Generated by create-nx-workspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextTopLoader color="#4f46e5" showSpinner={false} />
        <Providers>
          <ToastProvider>{children}</ToastProvider>
        </Providers>
      </body>
    </html>
  );
}
